<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="SkiaSharp" Version="3.119.2-preview.1" />
    <PackageReference Include="Topten.RichTextKit" Version="0.4.167" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Styles\VecTiles.Styles.OpenMapTiles\VecTiles.Styles.OpenMapTiles.csproj" />
    <ProjectReference Include="..\VecTiles.Renderers.Common\VecTiles.Renderers.Common.csproj" />
  </ItemGroup>

</Project>
